### ISSUE TITLE
Panics with multiple outputs

### ISSUE THREAD

**Issue by henke1010** [TLmaK0/rustneat#23]
Hello! I'm using this library to try to make bot for a game as a learning experience but struggle with generating multiple outputs. Might be something that I do wrong but the following example code panics:
```
impl Environment for XORClassification {
    fn test(&self, organism: &mut Organism) -> f64 {
        let mut output = vec![0f64, 0f64]; // Doesn't panic with vec![0f64]

        let mut distance: f64;

        organism.activate(&vec![0f64, 0f64], &mut output);
        distance = (0f64 - output[0]).abs(); // [0, 0] should generate output 0
        organism.activate(&vec![0f64, 1f64], &mut output);
        distance += (1f64 - output[0]).abs(); // [0, 1] should generate output 1
        organism.activate(&vec![1f64, 0f64], &mut output);
        distance += (1f64 - output[0]).abs(); // [1, 0] should generate output 1
        organism.activate(&vec![1f64, 1f64], &mut output);
        distance += (0f64 - output[0]).abs(); // [1, 1] should generate output 0

        (4f64 - distance).powi(2)
    }
}
```

Error:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\projects\rust\src\libcore\slice\mod.rs:865:10
note: Run with `RUST_BACKTRACE=1` for a backtrace
```

While this example generates outputs as expected:
```
impl Environment for XORClassification {
    fn test(&self, organism: &mut Organism) -> f64 {
        let mut output = vec![0f64];

        let mut distance: f64;

        organism.activate(&vec![0f64, 0f64], &mut output);
        distance = (0f64 - output[0]).abs(); // [0, 0] should generate output 0
        organism.activate(&vec![0f64, 1f64], &mut output);
        distance += (1f64 - output[0]).abs(); // [0, 1] should generate output 1
        organism.activate(&vec![1f64, 0f64], &mut output);
        distance += (1f64 - output[0]).abs(); // [1, 0] should generate output 1
        organism.activate(&vec![1f64, 1f64], &mut output);
        distance += (0f64 - output[0]).abs(); // [1, 1] should generate output 0

        (4f64 - distance).powi(2)
    }
}
```

Why is this?
Also, great library otherwise, will see if I can solve it and close this issue if it's some blunder on my part which is highly likely.

Here's the backtrace:
```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\projects\rust\src\libcore\slice\mod.rs:865:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:

  ...

   9: core::panicking::panic_bounds_check
             at C:\projects\rust\src\libcore\panicking.rs:58
  10: core::slice::{{impl}}::index<f64>
             at C:\projects\rust\src\libcore\slice\mod.rs:865
  11: core::slice::{{impl}}::index<f64,usize>
             at C:\projects\rust\src\libcore\slice\mod.rs:767
  12: alloc::vec::{{impl}}::index<f64,usize>
             at C:\projects\rust\src\liballoc\vec.rs:1706
  13: rustneat::organism::Organism::activate
             at E:\prog\rust\rustneat\src\organism.rs:57
  14: neatctrl::{{impl}}::test
             at .\src\main.rs:50
  15: rustneat::species_evaluator::{{impl}}::evaluate_organisms::{{closure}}
             at E:\prog\rust\rustneat\src\species_evaluator.rs:93
  16: crossbeam::scoped::{{impl}}::spawn::{{closure}}<closure,()>
             at C:\Users\Henrik\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.2.12\src\scoped.rs:237
  17: crossbeam::{{impl}}::call_box<closure>
             at C:\Users\Henrik\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.2.12\src\lib.rs:44
  18: crossbeam::spawn_unsafe::{{closure}}<closure>
             at C:\Users\Henrik\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-0.2.12\src\lib.rs:53
```

EDIT:
I think I solved it! (EDIT: Nvm I didn't) By changing 
https://github.com/TLmaK0/rustneat/blob/18b4fbfba6c2132f305e784ad7f4af4076c23f19/src/organism.rs#L54-L59

to 

```
        if sensors.len() < neurons_len {
            let outputs_activations = activations.split_at(sensors.len()-1).1.to_vec();
            for n in 0..outputs.len()-1 {
                outputs[n] = outputs_activations[n];
            }
        }
```

I managed to get the XOR example with multiple outputs to work and generate a fitness > 15.9
EDIT: This comes with a lot of issues however, first, all other outputs expect output[0] remains zero and doesn't evolve and it doesn't work with single outputs anymore. But it did solve the panic, so I atleast came one step closer to solve it :) 👍 

EDIT: 
Fixed it! With:
https://github.com/henke1010/rustneat/blob/c813b555a714c5b85b7c84fc5ee103e1d60a8ae3/src/organism.rs#L54-L63

Made a pull request

**Comment by henke1010** [comment]
Made a pull request, closing this issue.
